### PR TITLE
Amanda

### PR DESCRIPTION
**Pull request by amandat85**
This a new branch where  I will keep all my work. I have changed the navbar six times each time it is overridden by something else. I have also changed the login form and the login form several times. I have tested the pages I have changed and there are no errors and they render correctly.

### CODE REVIEW

**Comment by legendarybrij** [comment]
Amanda you are still using the old branch. Make sure you do git pull again and then copy and paste changes from these branch.

**Comment by amandat85** [comment]
> Amanda you are still using the old branch. Make sure you do git pull again and then copy and paste changes from these branch.

How can it be an old branch if I only made it at around 12:00pm and git pulled prior to that?

**Comment by amandat85** [comment]
I just pulled and it says everything is up to date.

**Comment by legendarybrij** [comment]
All good now Amanda. Cheers!!

**Comment by legendarybrij** [comment]
Screen Shot 2019-07-03 at 7 02 22 PM

**Pull request merged**
