### PR TITLE
Amanda

### PR DESCRIPTION
**Pull request by amandat85**
This is the restyled found.js page. It is completely different so there will be merge conflicts. I've integrated the text that was added for the title of the object that was updated.

### CODE REVIEW

**Comment by amandat85** [comment]
> This is the restyled found.js page. It is completely different so there will be merge conflicts. I've integrated the text that was added for the title of the object that was updated.

I fixed the conflict. It should be good. Also added lost.

**Comment by legendarybrij** [comment]
Screenshot (1)
Screenshot (2)
Screenshot (3)
Screenshot (4)

**Comment by amandat85** [comment]
The images are for what? If it's to say it's not fully mobile compatible I know. I'm not finished.

**Comment by legendarybrij** [comment]
Amanda your new changes are not responsive and don't change the type of text field I used before. Check out before and after. It looked good when you click on it the input label message becomes smaller. Just change the color of fields.

**Comment by amandat85** [comment]
> Amanda your new changes are not responsive and don't change the type of text field I used before. Check out before and after. It looked good when you click on it the input label message becomes smaller. Just change the color of fields.

I just said I know they are not response and the text fields before are hard to read, but if you have to have them fine.

**Comment by legendarybrij** [comment]
> > Amanda your new changes are not responsive and don't change the type of text field I used before. Check out before and after. It looked good when you click on it the input label message becomes smaller. Just change the color of fields.
> 
> I just said I know they are not response and the text fields before are hard to read, but if you have to have them fine.

If you want increase the size of fonts its style, if you think it is small.

**Comment by legendarybrij** [comment]
Also Amanda. Can you make sure you don't change any id's or class name? and if you have, then change it back and restore it like before. Because i will need that for inserting into database.

**Comment by legendarybrij** [comment]
Amanda....
Screen Shot 2019-07-05 at 9 41 18 PM
The cloudUpload icon won't work. It is different version of material UI. I liked that icon too lol and tried that before but got same error.

**Pull request closed without merging**
